language: node_js

node_js:
  - lts/*

script:
  - npm run build

deploy:
  local-dir: build
  provider: pages
  fqdn: schedule.theowly.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
